// ============================================================
// SIP RESEARCH - Base documental
// Fuente: Anales de Salud Mental (INSM "Honorio Delgado - Hideyo Noguchi") y portal institucional gob.pe
// ============================================================

10) : null;
}const data = [
{ id:"REG-001", titulo:"Estudio Epidemiológico de Salud Mental en la Sierra Peruana 2003", region:"Sierra Peruana", ciudad:"Ayacucho/Cajamarca/Huaraz", anio_estudio:"2003", anio_pub:2004, volumen:"19", numero:"1 y 2", paginas:"1-218", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/3", fuente:"Anales de Salud Mental", prevalencia:37.3, prevalencia_definicion:"Prevalencia de vida de cualquier trastorno psiquiátrico", resumen_breve:"Estudio epidemiológico de salud mental en la Sierra Peruana." },
{ id:"REG-002", titulo:"Estudio Epidemiológico de Salud Mental en las Ciudades de Cusco y Huancayo 2011", region:"Sierra Andina", ciudad:"Cusco/Huancayo", anio_estudio:"2011", anio_pub:2014, volumen:"29", numero:"1 y 2", paginas:"1-373", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/5", fuente:"Anales de Salud Mental", prevalencia:30.9, prevalencia_definicion:"Vida: Cusco 30,9%; Huancayo 30,0%.", resumen_breve:"Indicadores de salud mental en ciudades andinas." },
{ id:"REG-003", titulo:"Estudio Epidemiológico de Salud Mental en Hospitales Regionales 2015", region:"Hospitales Regionales", ciudad:"Abancay/Arequipa/Huancavelica/Iquitos/Pucallpa/Tacna/Trujillo/Tumbes", anio_estudio:"2015", anio_pub:2019, volumen:"35", numero:"1", paginas:"1-257", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/18", fuente:"Anales de Salud Mental", prevalencia:44.2, prevalencia_definicion:"Vida 44,2%; anual 18,9%; 6 meses 16,4%; actual 12,2%.", resumen_breve:"Estudio en hospitales regionales." },
{ id:"REG-004", titulo:"Estudio Epidemiológico de Salud Mental en la Sierra Peruana: ciudad de Ayacucho 2003", region:"Sierra Peruana", ciudad:"Ayacucho", anio_estudio:"2003", anio_pub:2004, volumen:"19", numero:"1 y 2", paginas:"", tema:"Epidemiología", url:"https://cdn.www.gob.pe/uploads/document/file/3660223/Estudio%20Epidemiol%C3%B3gico%20de%20Salud%20Mental%20en%20la%20Sierra%20Peruana%202003.pdf.pdf", fuente:"GOB.PE / INSM", resumen_breve:"Informe completo del estudio de Sierra Peruana 2003 con foco en Ayacucho." },
{ id:"REG-005", titulo:"Estudio Epidemiológico de Salud Mental en Lima Metropolitana y Callao - Replicación 2012", region:"Lima Metropolitana y Callao", ciudad:"Lima/Callao", anio_estudio:"2012", anio_pub:2013, volumen:"29", numero:"Suplemento 1", paginas:"1-397", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/7", fuente:"Anales de Salud Mental", prevalencia:26.1, prevalencia_definicion:"Vida 26,1%; 12 meses 11,8%.", resumen_breve:"Replicación del estudio basal de Lima y Callao." },
{ id:"REG-006", titulo:"Estudio Epidemiológico de Salud Mental en Lima Metropolitana 2002", region:"Lima Metropolitana y Callao", ciudad:"Lima/Callao", anio_estudio:"2002", anio_pub:2003, volumen:"18", numero:"1 y 2", paginas:"1-200", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/1", fuente:"Anales de Salud Mental", prevalencia:37.3, prevalencia_definicion:"Vida cualquier trastorno 37,3%; actual 23,5%.", resumen_breve:"Primer informe de la serie de Lima Metropolitana y Callao." },
{ id:"REG-007", titulo:"Estudio Epidemiológico de Salud Mental en la Ciudad de Chiclayo 2019", region:"Costa Norte", ciudad:"Chiclayo", anio_estudio:"2019", anio_pub:2023, volumen:"39", numero:"1", paginas:"1-281", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/490", fuente:"Anales de Salud Mental", prevalencia:31.9, prevalencia_definicion:"Vida cualquier trastorno 31,9%; 12 meses 14,5%.", resumen_breve:"Estudio regional de salud mental en Chiclayo." },
// REG-008 retirado por duplicidad de REG-001.
// REG-009a fusionado en REG-003.
{ id:"REG-010", titulo:"Confiabilidad y Validez de los Cuestionarios de los Estudios Epidemiológicos de Salud Mental de la Sierra Rural 2008 y Trapecio Andino 2010", region:"Sierra Rural y Trapecio Andino", ciudad:"Sierra Rural / Trapecio Andino", anio_estudio:"2008/2010", anio_pub:2024, volumen:"39", numero:"2", paginas:"1-288", tema:"Metodología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/488", fuente:"Anales de Salud Mental", resumen_breve:"Artículo metodológico asociado a instrumentos." },
{ id:"REG-011", titulo:"Estudio Epidemiológico de Salud Mental en Niños y Adolescentes en Lima Metropolitana en el contexto de la COVID-19, 2020", region:"Lima Metropolitana", ciudad:"Lima Metropolitana", anio_estudio:"2020", anio_pub:2021, volumen:"37", numero:"2", paginas:"", tema:"Salud Mental Infantil", url:"https://www.gob.pe/institucion/insm/informes-publicaciones/3510277-estudio-epidemiologico-de-salud-mental-en-ninos-y-adolescentes-en-lima-metropolitana-en-el-contexto-de-la-covid-19-2020", fuente:"GOB.PE / INSM", resumen_breve:"Estudio en 2.639 niños y adolescentes." },
{ id:"REG-012", titulo:"Investigación Epidemiológica en Psiquiatría y Salud Mental", region:"Perú", ciudad:"Perú", anio_estudio:"2001-2024", anio_pub:2024, volumen:"39", numero:"2", paginas:"", tema:"Marco Epidemiológico", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/269", fuente:"Anales de Salud Mental", resumen_breve:"Revisión de investigación epidemiológica en psiquiatría y salud mental en Perú." },
{ id:"REG-013", titulo:"Estudio Epidemiológico de Salud Mental en Arequipa, Moquegua y Puno 2018", region:"Sur del Perú", ciudad:"Arequipa/Moquegua/Puno", anio_estudio:"2018", anio_pub:2022, volumen:"38", numero:"2", paginas:"1-459", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/24", fuente:"Anales de Salud Mental", prevalencia:29.5, prevalencia_definicion:"Vida: Arequipa 28,5%; Moquegua 31,6%; Puno 35,4%.", resumen_breve:"Estudio epidemiológico del sur del Perú." },
{ id:"REG-014", titulo:"Estudio Epidemiológico de Salud Mental en Hospitales Generales y Centros de Salud de Lima Metropolitana 2015", region:"Lima Metropolitana y Callao", ciudad:"Lima/Callao", anio_estudio:"2015", anio_pub:2018, volumen:"34", numero:"1", paginas:"1-172", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/15", fuente:"Anales de Salud Mental", prevalencia:37.2, prevalencia_definicion:"Vida cualquier trastorno mental 37,2% en adultos atendidos.", resumen_breve:"Salud mental en población adulta atendida en establecimientos de Lima." },
{ id:"REG-015", titulo:"Estudio Epidemiológico de Salud Mental en Ayacucho, Cajamarca y Huaraz 2017", region:"Sierra Peruana", ciudad:"Ayacucho/Cajamarca/Huaraz", anio_estudio:"2017", anio_pub:2020, volumen:"36", numero:"1 y 2", paginas:"1-449", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/19", fuente:"Anales de Salud Mental / INSM", prevalencia:34.4, prevalencia_definicion:"Adultos: prevalencia de vida de cualquier trastorno psiquiátrico total 34,4% (IC95% 32,4-36,5); Huaraz 36,6%, Ayacucho 39,7%, Cajamarca 27,6%.", resumen_breve:"Replicación 2017 del estudio de Sierra Peruana 2003. Incluye adultos, adolescentes, adultos mayores y mujeres unidas; salud mental general, trastornos CIE-10, suicidio, sustancias, violencia, cognición, discapacidad, sueño, acceso, calidad de vida y determinantes." },
{ id:"REG-016", titulo:"Estudio Epidemiológico de Salud Mental en la Ciudad de Abancay 2016", region:"Sierra Sur", ciudad:"Abancay", anio_estudio:"2010/2016", anio_pub:2019, volumen:"35", numero:"2", paginas:"1-118", tema:"Epidemiología", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/16", fuente:"Anales de Salud Mental", prevalencia:27.5, prevalencia_definicion:"Cualquier trastorno mental: vida 28,8% (2010) y 27,5% (2016); 12 meses 13,5% y 14,6%.", resumen_breve:"Seguimiento epidemiológico de salud mental en Abancay." },
{ id:"REG-017", titulo:"Informe General de la Violencia Contra las Mujeres Actualmente Unidas y Alguna Vez Unidas en Hospitales Generales y Centros de Salud de Lima Metropolitana 2015", region:"Lima Metropolitana", ciudad:"Lima Metropolitana", anio_estudio:"2015", anio_pub:2021, volumen:"37", numero:"1", paginas:"1-228", tema:"Violencia contra la mujer", url:"https://openjournal.insm.gob.pe/revistasm/asm/article/view/22", fuente:"Anales de Salud Mental", resumen_breve:"Resultados sobre violencia contra mujeres actualmente unidas y alguna vez unidas en establecimientos de salud de Lima Metropolitana." }
];

function anioEjecucion(estudio){
  if (!estudio || !estudio.anio_estudio) return null;
  const match = String(estudio.anio_estudio).match(/\d{4}/);
  return match ? parseInt(match[0],
